
# Eignvectors from Eigenvalues

Papaer: https://arxiv.org/abs/1908.03795


In [105]:
import numpy.random
import numpy.linalg as LA

import numpy as np
import scipy as sp

In [106]:
# Generate Hermitian 
n = 5 
A = np.random.random_sample((n, n))
A = A + A.T

A

array([[1.10734586, 0.69826139, 0.85450227, 1.23784275, 0.93296744],
       [0.69826139, 0.28973321, 0.70949554, 0.99778883, 0.60094674],
       [0.85450227, 0.70949554, 1.48771461, 1.18879793, 1.48569274],
       [1.23784275, 0.99778883, 1.18879793, 0.89232543, 0.93979878],
       [0.93296744, 0.60094674, 1.48569274, 0.93979878, 1.46443136]])

In [114]:
# Calculate Eignvalues of A
w, v = np.linalg.eig(A)

(w, v)

(array([ 5.05698748,  0.73710632,  0.13018355, -0.52350948, -0.1592174 ]),
 array([[ 0.42669068,  0.54629973,  0.50924115, -0.26548431, -0.43552635],
        [ 0.2987156 ,  0.28697846, -0.34329407, -0.58441577,  0.60746995],
        [ 0.52106583, -0.43768337, -0.49630593, -0.18381458, -0.50677045],
        [ 0.45913994,  0.37868344, -0.27801706,  0.73907004,  0.14923591],
        [ 0.4963718 , -0.53313421,  0.54700053,  0.089241  ,  0.4027523 ]]))

In [108]:
X = np.power(v, 2) 
X.shape

(5, 5)

In [109]:
def submatrix(A, i):
    return np.delete(np.delete(A, i, axis=1), i, axis=0).T

M = [ np.linalg.eig(submatrix(A, i))[0] for i in range(n)]

np.array(M).shape

(5, 4)

In [110]:
A, submatrix(A, 3)

(array([[1.10734586, 0.69826139, 0.85450227, 1.23784275, 0.93296744],
        [0.69826139, 0.28973321, 0.70949554, 0.99778883, 0.60094674],
        [0.85450227, 0.70949554, 1.48771461, 1.18879793, 1.48569274],
        [1.23784275, 0.99778883, 1.18879793, 0.89232543, 0.93979878],
        [0.93296744, 0.60094674, 1.48569274, 0.93979878, 1.46443136]]),
 array([[1.10734586, 0.69826139, 0.85450227, 0.93296744],
        [0.69826139, 0.28973321, 0.70949554, 0.60094674],
        [0.85450227, 0.70949554, 1.48771461, 1.48569274],
        [0.93296744, 0.60094674, 1.48569274, 1.46443136]]))

In [112]:
V = np.zeros((n, n))
for i in range(n):
    a = np.prod(w[i] - np.delete(w, i))
    for j in range(n):
        b = np.prod(w[i] - M[j])
        V[i][j] = b/a
        
V.flatten(), X.T.flatten()

(array([0.18206494, 0.08923101, 0.2715096 , 0.21080948, 0.24638497,
        0.29844339, 0.08235664, 0.19156673, 0.14340115, 0.28423209,
        0.25932655, 0.11785082, 0.24631958, 0.07729348, 0.29920957,
        0.07048192, 0.34154179, 0.0337878 , 0.54622453, 0.00796396,
        0.1896832 , 0.36901974, 0.25681629, 0.02227136, 0.16220942]),
 array([0.18206494, 0.08923101, 0.2715096 , 0.21080948, 0.24638497,
        0.29844339, 0.08235664, 0.19156673, 0.14340115, 0.28423209,
        0.25932655, 0.11785082, 0.24631958, 0.07729348, 0.29920957,
        0.07048192, 0.34154179, 0.0337878 , 0.54622453, 0.00796396,
        0.1896832 , 0.36901974, 0.25681629, 0.02227136, 0.16220942]))